### PR TITLE
Fix build with Xamarin.Mac 2.0

### PR DESCRIPTION
**Pull request by mhutch**
* NSAttributedString constants have moved
* `System.Drawing.*F` to `CoreGraphics.CG*` conversions are gone

This will break the build with older versions. The conversions are fine but renamed constants won't work.

### CODE REVIEW

**Comment by slluis** [comment]
Will this still build for Xamarin.Mac < 2.0 ?

**Comment by Therzok** [comment]
Nope. NSStringAttributeKey is a breaking change.

**Comment by jstedfast** [comment]
Please please please can we merge this? I'm having to constantly switch between Xamarin.Mac 1.2 and 2.0 and this is driving me insane.

**Comment by jstedfast** [comment]
I *only* need Xamarin.Mac 1.2 to build XS...

**Comment by sevoku** [comment]
I can't test anything at the moment.

@slluis: maybe it is a good point to freeze a [0.2 branch](https://github.com/mono/xwt/milestones/v0.2) (or tag it at least) and proceed with Xamarin.Mac 2.0 on master, since there are some other breaking changes to check/merge? Should we proceed without CI and NuGet for Mac for now?

**Pull request merged**
