### PR TITLE
L10n

### PR DESCRIPTION
**Pull request by elsupergomez**
Use Mono.Posix for Catalog to translate string.
This add Mono.Unix using and encapsulate string with Catalog.GetString()
In some cases use string.Format() to replace string concatenation.

### CODE REVIEW

**Comment by Therzok** [comment]
cc @slluis @sevoku Wouldn't it be better to use ResX for localization on new projects?

**Comment by Therzok** [comment]
That way we do not depend on Mono.Unix on Windows too :)

**Comment by sevoku** [comment]
ResX would be better, but I think that its even better to keep the Xwt translation API as simple and generic as possible, allowing to use any translation technique. See my proposal in https://github.com/mono/xwt/pull/629.

**Comment by elsupergomez** [comment]
I like to know how use Xwt translation API for translate, as a example, to Spanish.

**Comment by sevoku** [comment]
@elsupergomez: I've merged #629. The API is really simple, you need to implement the `ITranslationCatalog` (https://github.com/mono/xwt/blob/master/Xwt/Xwt/ITranslationCatalog.cs#L29-L33) interface and assign your implementation to the new `Application.TranslationCatalog` property (https://github.com/master/xwt/blob/master/Xwt/Xwt/Application.cs#L66).

**Comment by elsupergomez** [comment]
It is really simple. I like it.

**Pull request closed without merging**
