### PR TITLE
Use Dispatcher to Dispose of a Window

### PR DESCRIPTION
**Pull request by steffenWi**
... if the Dispose was called from a seperate thread than the window belongs to.

### CODE REVIEW

**Comment by steffenWi** [comment]
Hi,

why is this not merged? Are there any problems with my code?

**Comment by sevoku** [comment]
The code is ok! Works for me. But the commit history is confusing. Can you rebase so it is one single commit containing the relevant change only, please?

**Comment by steffenWi** [comment]
history fixed and formatting in extra commit

**Comment by steffenWi** [comment]
@sevoku hey, does this look ok to you?

**Comment by steffenWi** [comment]
@sevoku you there?

**Comment by Therzok** [comment]
The problem is that we do not use VS style as a coding style in Xwt. I opened https://github.com/mono/xwt/pull/558/files with just the functional change.

**Pull request closed without merging**
