### PR TITLE
Add TextInput to KeyEvent (was: Fixed WPF KeyCode)

### PR DESCRIPTION
**Pull request by cra0zy**
"(int)e.Key" just returned the enum value instead of ascii code

### CODE REVIEW

**Comment by sevoku** [comment]
KeyEventArgs should be created with the native key code as the second argument and not its unicode or ascii representation:

```c#
public KeyEventArgs (Key key, int nativeKeyCode, ModifierKeys modifiers, bool isRepeat, long timestamp)
```

With your change KeyEventArgs.NativeKeyCode would not be correct.

What we need here is an additional String property in KeyEventArgs which should contain the characters, if any. And you can use the TextInput event, too.

**Comment by cra0zy** [comment]
> With your change KeyEventArgs.NativeKeyCode would not be correct.

Sorry, I misunderstood what the number should be doing.

> What we need here is an additional String property in KeyEventArgs which should contain the characters, if any. And you can use the TextInput event, too.

Ok, easy enough, will update this tomorrow morning.

**Comment by sevoku** [comment]
I can't test this atm. How about Mac and Gtk?

**Comment by cra0zy** [comment]
> I can't test this atm. How about Mac and Gtk?

With this I only update Gtk and Wpf.

Since I don't own a Mac I can't update the Mac side so I just added a new constructor method for KeyEventArgs so I don't break something.

**Pull request closed without merging**
