### PR TITLE
Merge WPF specific, Thread safe window closing

### PR DESCRIPTION
**Pull request by steffenWi**
Make sure a window is closed, regardless of which thread tried to close it.

### CODE REVIEW

**Comment by steffenWi** [comment]
I'm not sure where the conflict is. To me it looks fine.

**Comment by Therzok** [comment]
I've already merged your fix from your previous PR some time ago manually.

https://github.com/mono/xwt/blob/master/Xwt.WPF/Xwt.WPFBackend/WindowFrameBackend.cs#L68-L75

**Comment by Therzok** [comment]
https://github.com/mono/xwt/pull/488 -> https://github.com/mono/xwt/pull/558

**Comment by steffenWi** [comment]
Sorry about that. Don't know why it showed up.

**Pull request closed without merging**
