### PR TITLE
#315 - Extends NSOutlineView for proper handling mouse events

### PR DESCRIPTION
**Pull request by Strnadj**
Iam referencing my Issue #315 from thursday, I have to fix this issue, cause I need it ;) It's something like "example solution", Iam new in Mono / Mono Mac / c#, but it works... I try to find mouse handler for List / TreeView but I was no able to find it... I have to extend NSOutlineView, like "Hywel Thomas" does it in "WidgetView".

### CODE REVIEW

**Comment by sevoku** [comment]
Isn't this the same as #328 but for TreeViews? Could you move the sample from the main window to the TreeViews sample?

**Comment by Strnadj** [comment]
@sevoku Yes its actually is, Iam now in middle of sth, I accidentally deleted my fork of mono/xwt. I will move examples to treeview, rebase it and create new PR, but probably tomorrow..

**Comment by sevoku** [comment]
Sure, no problem! Take the time you need!

**Comment by Strnadj** [comment]
Close this, accidentaly deleted XWT branch...

**Pull request closed without merging**
