### PR TITLE
Add ListViewColumn and CellView expansion

### PR DESCRIPTION
**Pull request by sevoku**
This patch adds expansion support for ListView/TreeView columns and cells.
New API:
* `ListViewColumn.Expands`: the column expands to fill all available space inside the view.
* `CellView.Expands`: the cell view expands horizontally to fill all available space inside its column. Due to toolkit limitations CellView expanding can be only set upon creation, `CellView.Expands` is read only.

TODO: Wpf column expansion

### CODE REVIEW

**Comment by slluis** [comment]
I feel it would be more consistent if the expand argument is specified when adding the cell to the cellview collection. `CellViewCollection` could have overloads for Add and Insert that take an `expands` argument (which could still be internally stored in CelllView).

**Comment by sevoku** [comment]
Yeah, that's a good idea! Done: f745dc8
The CellView constructor parameter is still useful I think, or should we remove it now?

**Comment by slluis** [comment]
I would remove it now.

**Comment by sevoku** [comment]
ok, done

**Comment by garuma** [comment]
Merged since we need this for one of our feature work.

**Pull request merged**
