### PR TITLE
Iconeria: resolution independent icons 

### PR DESCRIPTION
**Pull request by lytico**
including  http://fortawesome.github.io/Font-Awesome/
(Version 4.04)
usage:
var icons = new AwesomeIconeria {Fill = true,FillColor = Colors.White,
							Stroke = true,StrokeColor = Colors.Black};
// make an icon with 36 pixels:
var img = Iconeria.AsImage (icons.FaThumbsUp, 36);

Background:
AwesomeIconeria (see file: AwesomeIconeria-4.04.Generated.cs) has a method for each icon. This methods have been gererated with a tool (https://github.com/lytico/svgpath2code/tree/MonoXwtVersion) out of the font-definitions of Font Awesome.

### CODE REVIEW

**Comment by sevoku** [comment]
I don't really understand how this works. We have to add a drawing method for every stock icon (marked with the IconAttribute)? Or is it a way for the user to implement own icons and why should this be part of Xwt then?

**Comment by lytico** [comment]
Yes, there IS a drawing method for each font awesome icon, see file:
AwesomeIconeria-4.04.Generated.cs
You have do click SHOW, as it is not expanded in the standard view of github, cause its too big

**Comment by sevoku** [comment]
Aaah! Sorry, I didn't see that! Nice!
But I'm still not sure about adding this to Xwt itself. If there would be a project for different platforms, then this could be added there, like I did it for [Oxyplot](http://oxyplot.org/announcements/). But it looks like there are tons of different specialized projects (Wpf, Xamarin,...) on [NuGet](http://www.nuget.org/packages?q=FontAwesome). We could create a new separate Project (something like FontAwesome.Xwt) and bind it to an Xwt NuGet package (when it gets released).

**Comment by lytico** [comment]
It could be with more icon sets, they only need to have svgpath definition. eg. https://github.com/GNOME/adwaita-icon-theme (as you suggested in https://github.com/mono/xwt/issues/470) would be possible too, it needs only adoption of the svg to xwt-code converter.
With project you mean github project, not c#-project, I suppose?

**Comment by sevoku** [comment]
Concerning #470: thats the point. The idea behind StockIcons is to use native icons (which come from the platform itself and can change depending on platform release (Gnome 2 or 3, Windows 7/Windows 8,...) and user settings (e.g. Gtk Themes). My idea is to make them replaceable from the user side.

Your proposal is a really nice way for the user to generate custom static icons, which is independent of #470 and the idea behind Xwt or StockIcons. So yes I really mean a separate development project (on GitHub or wherever), which could include a generator for custom icon sets and more. @slluis: what do you think?

Generator: how does it work? Do you have some code? Btw: I'd like to implement Svg support for Xwt (load images from svg using a special backends like rsvg with Gtk) but this is an other story...

**Comment by lytico** [comment]
Generator: https://github.com/lytico/svgpath2code/tree/MonoXwtVersion
its a modified version of https://github.com/spouliot/svgpath2code . The problem is the license, its LGPL2, so it can't included in core xwt, otherwise it would be a good base for svg support

**Comment by sevoku** [comment]
Hhm, without a generator, it doesn't really make sense to add only this special icon set to Xwt. An own project should be the way to go, which should be LGPL licensed then. We could add a "Projects using Xwt" section to the Xwt readme.md with some links to projects like this one :+1:

**Comment by slluis** [comment]
I agree with Vsevolod, this doesn't really belong to XWT, it should be in its own repo.

**Comment by slluis** [comment]
However, let me add that this is very cool :)

**Comment by sevoku** [comment]
For sure! Really cool!

**Comment by sevoku** [comment]
I think we can close this. Let us know if you need some help with the project!

**Pull request closed without merging**
